version: "3.9"  # optional since v1.27.0
services:
  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/code
  #     - logvolume01:/var/log
  #   links:
  #     - redis
  meilisearch:
    image: getmeili/meilisearch
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/data.ms

  questdb:
    image: questdb/questdb
    ports:
      - "9000:9000"
      - "9009:9009/udp"
      - "8812:8812"
    volumes:
      - "questdb_data:/root/.questdb/db"
volumes:
    meilisearch_data: {}
    questdb_data: {}