version: "3.9"  # optional since v1.27.0
services:
  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/code
  #     - logvolume01:/var/log
  #   links:
  #     - redis
  meilisearch:
    image: getmeili/meilisearch
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/data.ms
volumes:
    meilisearch_data: {}